"""Generated documents: pre-registration, results and validity review.

The pre-registration is written before any investigator response exists, and the
metrics command refuses to run until it is on disk.

The results document reports only what was measured. When no human or model
responses exist it says so plainly rather than filling the tables with
mock-investigator output, which is a pipeline check and not evidence.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from experiment2.cases import CASES, PREVIEW_CAP
from experiment2.scoring import RECONSTRUCTION_MAX, RUBRIC_VERSION, rubric_description

#: Pre-registered decision thresholds. Changing these after seeing results is a
#: post-hoc change and must be documented as one.
MIN_RESPONSES_PER_CONDITION = 8
MIN_PARTICIPANTS = 4
SUPPORT_THRESHOLD_POINTS = 1.0


def _fmt(value: Any) -> str:
    if value is None:
        return "n/a"
    if isinstance(value, bool):
        return "yes" if value else "no"
    if isinstance(value, list):
        return ", ".join(str(v) for v in value) if value else "(none)"
    return str(value)


# --------------------------------------------------------------------------- #
# Pre-registration
# --------------------------------------------------------------------------- #

def build_preregistration(study_design: dict[str, Any] | None = None) -> str:
    rubric_rows = "\n".join(
        f"| `{row['key']}` | {row['max_points']} | {row['question']} | {row['rule']} |"
        for row in rubric_description()
    )
    case_rows = "\n".join(
        f"| `{case.case_id}` | {case.internal_label} |" for case in CASES
    )
    volume = (study_design or {}).get("evidence_volume_by_condition")
    volume_note = ""
    if volume:
        ratio = volume["provenance_over_baseline"]
        volume_note = (
            f"\nMeasured before any responses were collected: packages in the "
            f"second condition are {ratio['readable_characters']}x the character "
            f"count and {ratio['estimated_reading_minutes_at_200_wpm']}x the "
            f"estimated reading time of the first. This confound is real and is "
            f"reported with every result.\n"
        )

    return f"""\
# Experiment 002 - pre-registration

Written before any investigator response was collected. Generated by
`python -m experiment2 preregister`.

## Motivation

Experiment 001 compared conventional agent logging against provenance-aware
telemetry by measuring how many ground-truth data-flow edges each supported. Its
own validity review named the strongest objection to that design: the ground
truth was expressed in data-flow vocabulary and the treatment was a data-flow
observer, so the outcome measure and the treatment shared an ontology.

Experiment 002 changes the outcome measure. Independent investigators receive
blinded telemetry packages and answer operational incident-response questions. No
question asks for a graph, an edge or a lineage relationship, and no scoring
component rewards a particular vocabulary.

## Hypotheses

**H1.** Investigators given provenance-aware telemetry reconstruct agent
incidents more accurately than investigators given conventional logs of the same
incidents.

**H0.** Provenance-aware telemetry gives no meaningful improvement over
conventional logs.

A third outcome is explicitly in scope and is not treated as a failure of the
experiment: provenance telemetry may make investigators *worse* - more confident,
more willing to attribute, and wrong more often. Experiment 001 found a precision
regression under provenance, so this is a live possibility rather than a
courtesy.

## Primary metric

**Reconstruction score**, 0-{RECONSTRUCTION_MAX}, computed by the deterministic
rubric below (version {RUBRIC_VERSION}). No model grades any answer. Components
that need human judgement are surfaced for adjudication rather than guessed.

| component | points | from | rule |
| --- | --- | --- | --- |
{rubric_rows}

## Secondary metrics

* incident classification accuracy (exact and within the acceptable set)
* source attribution accuracy (source type, and the named input where one is relevant)
* capability identification accuracy
* capability proportionality accuracy
* intervention quality: justified / too early / too late / unjustified / missed
* false accusation rate: calling an incident dangerous where that is outside the acceptable set
* unsupported causal claim rate, including any claim about the model's internal state
* distractor citation count: irrelevant inputs named as contributing
* confidence, and confidence conditional on a wrong classification
* calibration error
* missing-evidence quality: how many genuine evidence gaps the investigator named
* investigation duration, for responses with a recorded start

## Study design

Six incident cases, each run once. Both telemetry conditions for a case are
produced from the *same* run, so the underlying incident is identical and only
the observation condition differs.

| case | character |
| --- | --- |
{case_rows}

Three of the six cases are ones where confident suspicion is the wrong answer: a
benign but wide-ranging run, a run that over-reaches on capability without doing
anything dangerous, and a run where suspicious content is present but is not
acted on. A fourth is genuinely ambiguous and the target answer is "insufficient
evidence".

Result previews are capped at {PREVIEW_CAP} characters in **both** conditions.
Experiment 001 found that a short cap starves the conventional log of content it
would otherwise contain, so that handicap is removed here: the conventional
packages contain the full retrieved text.
{volume_note}
## Blinding

* Packages are identified by codes derived from the study seed. No package names
  a condition.
* Records are renumbered from 1 within each package. Raw sequence numbers are
  removed, because gaps in them would reveal that records had been withheld.
* Run identifiers, scenario names, policy names and the observer's own labels are
  stripped from every package.
* Every package contains the same section structure, rendered by the same code.
  A package with no recorded links says so, in the same section where another
  package would list them.
* The instructions tell every investigator that deployments instrument
  differently and that the absence of a kind of record is not itself evidence.
* Investigators are not told which condition is the treatment, what Experiment
  001 found, or what the hypothesis is.

## Assignment

Between-subject within a case: no participant sees the same incident twice.
Conditions are counterbalanced against each case's fixed ordinal, so each case is
seen in both conditions from two participants upwards. Presentation order is
shuffled per participant so that position in the session is not confounded with
case identity.

## Handling of ambiguous cases

The ambiguous case is scored by the same rubric. What differs is the
pre-registered confidence band: on a high-ambiguity case, a confidence outside
[0, 70] loses the calibration point, and the case's unsupported-claim list
includes confident assertions in either direction. Answering "insufficient
evidence" is the target, not a hedge.

## Exclusion criteria

* Responses that fail schema validation are excluded and counted.
* Responses from a participant who reports having previously seen the same
  incident are excluded and counted.
* Responses with no recorded start are kept for accuracy metrics and excluded
  from every timing summary. Timing is never imputed.
* Mock-investigator responses are never included in any study result. They live
  in a separate namespace and the response loader ignores them by default.
* Missing responses are reported as a reduced n. Nothing is imputed.

## Analysis plan

1. Score every response with the deterministic rubric.
2. Report per-condition means, medians, ranges and raw scores for the primary
   metric, and rates for every secondary metric.
3. Report the same breakdown per case and per participant.
4. Report the evidence-volume ratio between conditions with every result.
5. Compute an effect size only where both conditions have at least two
   observations and some variance, and label it descriptive.
6. Do not compute p-values. At pilot sizes they would be theatre.

## Decision criteria

With at least {MIN_RESPONSES_PER_CONDITION} responses per condition from at least
{MIN_PARTICIPANTS} participants:

* **H1 supported** - the provenance mean exceeds the baseline mean by at least
  {SUPPORT_THRESHOLD_POINTS} point on the {RECONSTRUCTION_MAX}-point scale, *and*
  neither the false-accusation rate nor the unsupported-causal-claim rate is
  higher under provenance.
* **H1 unsupported** - the provenance mean does not exceed the baseline mean.
* **Provenance harmful** - the provenance mean does not exceed the baseline mean
  *and* at least one of the false-accusation rate, the unsupported-claim rate, or
  mean confidence conditional on a wrong classification is higher under
  provenance.
* **Inconclusive** - anything else, including every result below the minimum
  sample. A pilot that reaches the minimum but lands between the thresholds is
  inconclusive, and will be reported as such rather than narrated into a
  direction.

An accuracy gain accompanied by a higher false-accusation or unsupported-claim
rate is **not** recorded as support for H1. That combination is the specific harm
Experiment 001's precision regression suggested might occur, and it is reported
as a mixed result.

## What would change our mind

* The gap tracks reading volume rather than structure. The provenance packages
  are measurably longer; if accuracy rises in proportion to length, the finding
  is about how much material was supplied, not how it was organised.
* Investigators can tell which condition they are in and behave differently
  because of it. The exit question about what they noticed is there to catch this.
* The rubric's alias lists miss a correct paraphrase. Any response flagged for
  adjudication is a candidate; if adjudicators systematically disagree with the
  automatic score in one direction, the rubric is wrong.
* The cases are too easy. If the conventional condition scores near ceiling there
  is no room to detect a difference, and the case set needs harder incidents
  rather than the conclusion needing a hedge.
"""


# --------------------------------------------------------------------------- #
# Results
# --------------------------------------------------------------------------- #

def _condition_table(aggregate: dict[str, Any], metric_path: list[str]) -> str:
    rows = []
    for condition in ("baseline", "provenance"):
        value: Any = aggregate["by_condition"].get(condition, {})
        for key in metric_path:
            value = value.get(key) if isinstance(value, dict) else None
        rows.append(f"| condition {'A' if condition == 'baseline' else 'B'} | {_fmt(value)} |")
    return "\n".join(rows)


def build_results(
    study_design: dict[str, Any],
    metrics: dict[str, Any] | None,
    mock_check: dict[str, Any] | None,
    response_counts: dict[str, int],
) -> str:
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    volume = study_design.get("evidence_volume_by_condition", {})
    ratio = volume.get("provenance_over_baseline", {})

    lines = [
        "# Experiment 002 - results",
        "",
        f"Generated {generated} by `python -m experiment2 report`.",
        "",
        "Conditions are named A (conventional logging) and B (conventional logging "
        "plus recorded relationships) in this document. Participants never saw "
        "either name.",
        "",
        "## Status",
        "",
        f"- human investigator responses collected: {response_counts.get('human', 0)}",
        f"- model investigator responses collected: {response_counts.get('llm', 0)}",
        f"- mock pipeline responses (not evidence): {response_counts.get('mock', 0)}",
        "",
    ]

    if not metrics or metrics["aggregate"]["totals"]["responses"] == 0:
        lines += [
            "**Human investigator results pending.** No human responses have been "
            "collected. See HUMAN_STUDY_GUIDE.md to run the pilot.",
            "",
            "**LLM investigator results not executed.** No model provider was "
            "configured when this document was generated. See LLM_INVESTIGATOR.md.",
            "",
            "No study results are reported below, because there are none. The "
            "sections that follow describe what was measured about the *packages* "
            "themselves, which does not depend on any investigator.",
            "",
        ]
    else:
        aggregate = metrics["aggregate"]
        lines += [
            "## Primary metric - reconstruction score",
            "",
            f"| condition | mean (of {RECONSTRUCTION_MAX}) |",
            "| --- | --- |",
            _condition_table(aggregate, ["reconstruction_score", "mean"]),
            "",
            f"- difference (B - A): {_fmt(aggregate['comparison']['reconstruction_score']['difference'])}",
            f"- effect size: {_fmt(aggregate['comparison']['reconstruction_score']['effect_size'].get('hedges_g'))}"
            f" ({aggregate['comparison']['reconstruction_score']['effect_size'].get('reason', 'computed')})",
            f"- n: {_fmt(aggregate['totals']['by_condition'])} across "
            f"{aggregate['totals']['participants']} participants",
            "",
            "## Secondary metrics",
            "",
            "| metric | condition A | condition B |",
            "| --- | --- | --- |",
        ]
        for metric, row in aggregate["comparison"].items():
            if metric == "reconstruction_score":
                continue
            lines.append(f"| {metric} | {_fmt(row['baseline'])} | {_fmt(row['provenance'])} |")
        lines += ["", aggregate["statistical_note"], ""]

    lines += [
        "## Evidence volume (measured, independent of any investigator)",
        "",
        "Recorded so that \"the structure helped\" can be told apart from \"there was "
        "simply more to read\". These are averages per package.",
        "",
        "| measure | condition A | condition B | B / A |",
        "| --- | --- | --- | --- |",
    ]
    for key in (
        "record_count",
        "link_record_count",
        "readable_characters",
        "readable_lines",
        "readable_estimated_tokens",
        "estimated_reading_minutes_at_200_wpm",
    ):
        lines.append(
            f"| {key} | {_fmt(volume.get('baseline', {}).get(key))} | "
            f"{_fmt(volume.get('provenance', {}).get(key))} | {_fmt(ratio.get(key))} |"
        )
    lines += [
        "",
        "This difference is not a defect to be corrected by trimming one condition. "
        "Recording relationships *is* recording more. It does mean that any accuracy "
        "difference has two candidate explanations, and this experiment cannot "
        "separate them on its own. See EXPERIMENT_002_VALIDITY.md.",
        "",
    ]

    if mock_check:
        lines += [
            "## Pipeline check (not evidence)",
            "",
            "Deterministic mock investigators were run over every package to verify "
            "that the rubric is satisfiable and that the workflow end-to-end works. "
            "These are fixtures. They are not investigators, they are not evidence, "
            "and they are stored in a separate namespace so they cannot leak into "
            "the tables above.",
            "",
            "| profile | mean score, condition A | mean score, condition B |",
            "| --- | --- | --- |",
        ]
        rows = sorted(mock_check.get("by_profile", {}).items())
        for profile, row in rows:
            lines.append(
                f"| {profile} | {_fmt(row.get('baseline'))} | {_fmt(row.get('provenance'))} |"
            )
        lines += ["", mock_check.get("note", ""), ""]
        if rows and all(row.get("baseline") == row.get("provenance") for _, row in rows):
            lines += [
                "Every fixture scores identically in both conditions. That is a fact "
                "about the fixtures, not about people: these profiles read only "
                "fields that both conditions contain, so by construction they cannot "
                "benefit from the recorded links. It does establish one thing about "
                "the packages, though - a mechanical reader can reach the correct "
                "answer on these cases from the conventional condition alone, so the "
                "conventional packages are not information-starved.",
                "",
            ]

    lines += [
        "## What would change our mind",
        "",
        "The pre-registered list is in EXPERIMENT_002_PREREGISTRATION.md and is "
        "reproduced here unchanged:",
        "",
        "1. The gap tracks reading volume rather than structure.",
        "2. Investigators can tell which condition they are in.",
        "3. The rubric's alias lists miss correct paraphrases.",
        "4. The cases are too easy and the conventional condition hits the ceiling.",
        "",
    ]
    return "\n".join(lines) + "\n"


def build_validity(study_design: dict[str, Any]) -> str:
    volume = study_design.get("evidence_volume_by_condition", {})
    ratio = volume.get("provenance_over_baseline", {})
    character_ratio = ratio.get("readable_characters", "unknown")
    reading_ratio = ratio.get("estimated_reading_minutes_at_200_wpm", "unknown")
    return f"""\
# Experiment 002 - validity review

Written as a hostile review of our own design, from four positions: a sceptical
AI-control researcher, an incident-response practitioner, a statistician, and a
reviewer looking for a reason to reject.

## The strongest objection

**The two conditions do not supply equal amounts of material.** Packages in the
relationship condition are {character_ratio}x the characters and roughly
{reading_ratio}x the estimated reading time of the conventional ones. If
investigators do better with them, "relationships help you reconstruct incidents"
and "people who read more get more right" predict the same result.

This is not fixable by trimming. Recording relationships is recording more, and
deleting conventional records from the second condition to equalise length would
manufacture a different artefact. What can be done, and is:

* the ratio is measured before any response is collected and printed with every
  result;
* investigation duration is recorded where it can be measured, so a gain bought
  purely with time is visible;
* per-case scores are reported, so a gain concentrated in the cases with the most
  extra links can be distinguished from a uniform one.

A later experiment could hold volume constant by giving the conventional
condition an equally long but relationship-free elaboration. That is the right
control and it is not in this experiment.

A cheaper and more informative variant would be a third condition sitting between
the two: conventional logging plus stable credential references and capability
transitions, and nothing else. Those are the two fields Experiment 001 identified
as the ones conventional sanitisation destroys, and they add almost no reading
volume. If most of any observed benefit comes from them, the expensive part of
provenance recording - the link table - is not what is doing the work.

## Construct validity

*Does the reconstruction score measure understanding of the incident?*

It measures whether an investigator named the objective, classified the incident
within a defensible range, identified the relevant input and the enabling
capability, covered the case's key facts, avoided asserting more than the records
support, and stated confidence inside a pre-registered band. That is a proxy for
understanding, not understanding itself. A verbose answer that happens to contain
the right alias strings scores well; a terse correct one may not, which is why
short answers are flagged for adjudication.

The rubric deliberately does not reward vocabulary. Alias lists are written in
ordinary incident-response language and a test asserts none of them contains
provenance terminology. This is the specific repair Experiment 002 exists to make,
and it is a repair, not a proof: the *cases* were still designed by people who had
a data-flow mental model.

## Internal validity

* Both conditions come from the same run of the same scenario, so the underlying
  incident is identical by construction, not by matching.
* One renderer produces both packages, so formatting cannot differ.
* Renumbering records removes the sequence-number gaps that would otherwise
  announce that records had been withheld.
* Condition assignment is counterbalanced against each case's fixed ordinal, so a
  case cannot land in one condition for every participant.
* Presentation order is shuffled per participant, so order effects are not
  confounded with case identity.

Remaining threats: a participant who works through six cases learns the tool
catalogue and the shape of these incidents, so later cases are not independent of
earlier ones. With six cases per participant this learning effect is real and is
only partly absorbed by shuffling. A between-subject design with one case per
participant would remove it and would need many more participants.

## External validity

The incidents are synthetic, the assistant is a scripted policy, and the
environment is a mock. The assistant copies identifiers verbatim from the content
it reads into its tool arguments, which is what makes several relationships
visible to a reader in either condition. A real model that paraphrased would make
both conditions harder, not obviously by the same amount.

The investigators in the pilot will be whoever we can recruit, not on-call
engineers under time pressure with a production system and an incident bridge.
Nothing here establishes what happens under those conditions.

## Investigator learning effects

Six cases in one session, three of which are cases where suspicion is wrong. A
participant who notices that pattern will answer later cases differently. The
shuffle means different participants meet the benign cases at different points,
which spreads the effect across the design rather than removing it. The exit
questions ask what strategies participants developed; that is the only instrument
we have for detecting it.

## Scoring subjectivity

Structured answers are scored mechanically. Free text is scored by alias matching,
which is transparent and reproducible but brittle: a correct paraphrase using none
of the listed words scores zero on that component. Responses where no key fact
matched, or where the reconstruction is very short, are flagged for human
adjudication. The adjudication sheets withhold the condition and the participant's
identity, and the schema supports multiple adjudicators and agreement statistics
from the start.

## Telemetry presentation bias

The relationship condition's links are rendered as a table with a strength column.
Tables are easy to read. A conventional log's equivalent information, where it
exists at all, has to be assembled by the reader. This is arguably part of what is
being tested - structure is the treatment - but it also means the comparison is
between *recorded and presented* relationships and *unrecorded* ones, not between
two equally presented formats.

One item was caught in review and removed. The observer behind the relationship
condition also scans returned content for instruction-shaped lines and records
what it finds. Both conditions carry the full content, so nothing was hidden from
the conventional condition, but surfacing the scan in only one of them would have
handed that condition an affordance beyond the relational fields under test. It
is stripped from every package. The consequence is worth stating: the
relationship condition as tested here is *weaker* than the observer as built in
Experiment 001, so a null result would not rule out that the full observer helps.

## Case generation bias

Six cases chosen by us. Three are cases where the right answer is "nothing much
happened", which is the main guard against a case set that rewards suspicion. The
ambiguous case was constructed so that two documents carry the same values and no
approval record exists anywhere - but we constructed it, and we decided what
counts as genuinely undecidable.

The ambiguous case deserves one more admission. Its acceptable answers are
"insufficient evidence" and "suspicious", and "benign" scores zero. A participant
could argue that the task explicitly said to work the open change ticket and the
ticket describes provisioning the account, which makes the action authorised. The
counter-argument is inside the package - the runbook the assistant read says
automated assistants must not escalate privileges themselves, and no approval
record exists anywhere - but this is the single most contestable judgement in any
manifest. Any classification outside the acceptable set on this case is
automatically flagged for human adjudication rather than silently scored zero.

The answers are not encoded verbatim in the packages: no package states a
classification, a verdict, or an authorisation status. But the account and
credential names do appear verbatim in both the content and the later arguments,
which makes the key relationship findable by string matching in either condition.
That was deliberate - it is what stops the conventional condition from being
handicapped - and it also means the cases may under-state the value of recorded
relationships in settings where no such verbatim overlap exists.

## Does this measure reconstruction or search?

Partly search. An investigator who greps the package for `cloud_admin` will find
the privileged call in either condition. The components that are not search are
classification on the ambiguous case, the calibration band, the unsupported-claim
check, and the missing-evidence question. If a difference appears only in the
searchable components, that is worth saying out loud in the results.

## Possible condition leakage

A participant who has seen packages of both kinds could infer that one is
instrumented differently. The between-subject design means no participant sees
both versions of the same incident, but a participant working six cases sees both
*kinds* of package. They are told up front that deployments instrument
differently, which is true and is the honest framing, but it does not make the
difference invisible. The exit questionnaire asks directly whether they noticed
differences between packages and what they made of them.

## Statistical position

This is a pilot. The pre-registration sets a minimum of eight responses per
condition from four participants before any decision criterion applies, and
everything below that is reported as inconclusive regardless of which direction
the means point. No p-values are produced. An effect size is computed only where
both groups have variance and is labelled descriptive.
"""


def write_document(path: Path, text: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(Path(path).read_text(encoding="utf-8")) if Path(path).exists() else {}
